import '../scss/dep_styles.scss';
import * as bootstrap from 'bootstrap';
import * as comp from '../components/index';

comp.SetNotifications();
comp.Navbar();
comp.Sidebars();
comp.Footer();
comp.ProfileSidebarLeft();
comp.toggleTheme();
comp.Profile();
comp.Friends();
comp.Search();
comp.Stories();
comp.PostSender();
comp.Posts();
comp.MyFriendsRequests();
comp.MyPrivateMessages();
comp.MyNotifications();
comp.MyReactions();
comp.MyShares();
comp.MySharePost();
comp.EditMyPost(1);
comp.DelMyPost(1);
comp.setFixedNavbar();
comp.doActionBtnModals();