// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lcpsnapi.Context;

#nullable disable

namespace lcpsnapi.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20221220172852_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lcpsnapi.Classes.Achievements", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DateAchUnlocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjectiveCounter")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.Property<int?>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AttachmentId"));

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("PostsPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("PostsPostId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.Property<int?>("FriendsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FriendsId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFriends")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("FriendsId");

                    b.HasIndex("UsersId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.Property<int?>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("InfoId"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSchoolFinished")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUniversityFinished")
                        .HasColumnType("bit");

                    b.Property<int?>("LatestPostPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalComments")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReactions")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReplies")
                        .HasColumnType("int");

                    b.Property<int?>("TotalShares")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workorprofession")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoId");

                    b.HasIndex("LatestPostPostId");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Media", b =>
                {
                    b.Property<int?>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MediaId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateUploaded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Property<int?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PostId"));

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("ReactsId")
                        .HasColumnType("int");

                    b.Property<string>("Shortdesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Todo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DateT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfoId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Portugal",
                            Cover = "/assets/images/users/c_luigi.png",
                            DateBirthday = "1996-06-04T00:00:00",
                            DateRegistered = "2022-08-19T10:30:00",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            FirstName = "Luis",
                            Image = "/assets/images/users/luigi.png",
                            LastName = "Carvalho",
                            Password = "$2a$11$gitGW.zdbowemGY6T0LhleKYg3RlbvQ8jsibOVbbkb7M2GW5EVGHG",
                            Pin = "$2a$11$GkZfBLl9Z/fbJegZesqcb.e4hYuJhA56B3irnqgs6ARa19fHAOFpC",
                            PrivacyStatus = 0,
                            Role = 0,
                            Status = 1,
                            TypeFriend = 0,
                            Username = "luigicar96"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            Cover = "/assets/images/users/c_guest.png",
                            DateBirthday = "1995-05-03T00:00:00",
                            DateRegistered = "2022-08-31T15:50:00",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            FirstName = "Guest",
                            Image = "/assets/images/users/guest.png",
                            LastName = "Convidado",
                            Password = "$2a$11$1O7p.sl40VE8FTB2B32tEOdMq.LzBXo9BwCfh.I69Q2v0DLZW6tO6",
                            Pin = "$2a$11$QjcgWGg0OPZ4dljuzXI3o.NgyTDIx84OORCfBFOgFCOiCvjndy6.u",
                            PrivacyStatus = 1,
                            Role = 5,
                            Status = 0,
                            TypeFriend = 0,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.UsersToken", b =>
                {
                    b.Property<int?>("UsersTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UsersTokenId"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UsersTokenId");

                    b.ToTable("UserToken");

                    b.HasData(
                        new
                        {
                            UsersTokenId = 1,
                            DateCreated = new DateTime(2022, 12, 20, 17, 28, 52, 13, DateTimeKind.Utc).AddTicks(2726),
                            DateExp = "20/01/2023 17:28:52",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            Password = "$2a$11$.ox/2AEi7OqTsawayH3wzeiCtV9NA6/YqJZ1Ca34c5rMdQ8oQvX9i",
                            Pin = "$2a$11$XOnjpkXyPqtaaCl4SXT8/.qBpPqdXiK9mLmVIE3oSr4AIfDR1FRhK",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbGhvc3QiLCJqdGkiOiI3YWNiZDE1MS03MzYyLTQ1OGItYTkwYS0wYWY1NDk5MTY5MjUiLCJpYXQiOiIyMC8xMi8yMDIyIDE3OjI4OjUyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imx1aWdpY2FyOTYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJzdXBlcmFkbWluIiwiZXhwIjoxNjc0MjM1NzMyLCJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJsb2NhbGhvc3QifQ.95CKS4qlbh2kd-kWKOmHFsqexVwoWQY0Fbup8DyRaaI",
                            Username = "luigicar96",
                            UsersId = 1
                        },
                        new
                        {
                            UsersTokenId = 2,
                            DateCreated = new DateTime(2022, 12, 20, 17, 28, 52, 351, DateTimeKind.Utc).AddTicks(6631),
                            DateExp = "20/01/2023 17:28:52",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            Password = "$2a$11$WV2hIQ4lBTmn0v3wuCIZhexDWIC18L.LAIiHn0EWU8Y.0wWhdyoIO",
                            Pin = "$2a$11$o3FM4DOWzReBwWvcf3MT5uN171Dr/UasngkcS26mhhIEcEJbo9hx2",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbGhvc3QiLCJqdGkiOiIzMzVkYTY3Yy0zMzdmLTQwMjItOGZkNy03MzQ1NDJhMDFjM2UiLCJpYXQiOiIyMC8xMi8yMDIyIDE3OjI4OjUyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd1ZXN0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZ3Vlc3QiLCJleHAiOjE2NzQyMzU3MzIsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.gYBfAaO9PPr8ltBfLkBq0DXHLBBBrX2uxADFNSztLns",
                            Username = "guest",
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", null)
                        .WithMany("Attachments")
                        .HasForeignKey("PostsPostId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Users", null)
                        .WithMany("FriendsList")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", "LatestPost")
                        .WithMany()
                        .HasForeignKey("LatestPostPostId");

                    b.Navigation("LatestPost");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Info", "Info")
                        .WithMany()
                        .HasForeignKey("InfoId");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Navigation("FriendsList");
                });
#pragma warning restore 612, 618
        }
    }
}
