// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lcpsnapi.Context;

#nullable disable

namespace lcpsnapi.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230111133011_UpdateUserThingsInfoM")]
    partial class UpdateUserThingsInfoM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lcpsnapi.Classes.Achievements", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DateAchUnlocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjectiveCounter")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Animes", b =>
                {
                    b.Property<int?>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AnimeId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("AnimeId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.Property<int?>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AttachmentId"));

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("PostsPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("PostsPostId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ComicBooks", b =>
                {
                    b.Property<int?>("ComicBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ComicBookId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ComicBookId");

                    b.ToTable("ComicBook");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.Property<int?>("FriendsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FriendsId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFriends")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("FriendsId");

                    b.HasIndex("UsersId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryAnimes", b =>
                {
                    b.Property<int?>("GalleryAnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryAnimeId"));

                    b.Property<int?>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimesAnimeId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryAnimeId");

                    b.HasIndex("AnimesAnimeId");

                    b.ToTable("GalleryAnimes");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryComicBooks", b =>
                {
                    b.Property<int?>("GalleryComicBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryComicBookId"));

                    b.Property<int?>("ComicBookId")
                        .HasColumnType("int");

                    b.Property<int?>("ComicBooksComicBookId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryComicBookId");

                    b.HasIndex("ComicBooksComicBookId");

                    b.ToTable("GalleryComicBooks");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryGames", b =>
                {
                    b.Property<int?>("GalleryGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryGameId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryGameId");

                    b.HasIndex("GamesGameId");

                    b.ToTable("GalleryGames");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryMangas", b =>
                {
                    b.Property<int?>("GalleryMangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryMangaId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MangaId")
                        .HasColumnType("int");

                    b.Property<int?>("MangasMangaId")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryMangaId");

                    b.HasIndex("MangasMangaId");

                    b.ToTable("GalleryMangas");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryMovies", b =>
                {
                    b.Property<int?>("GalleryMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryMovieId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MoviesMovieId")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("GalleryMovies");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryTVSeries", b =>
                {
                    b.Property<int?>("GalleryTVSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GalleryTVSerieId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TVSerieId")
                        .HasColumnType("int");

                    b.Property<int?>("TVSeriesTVSerieId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GalleryTVSerieId");

                    b.HasIndex("TVSeriesTVSerieId");

                    b.ToTable("GalleryTVSeries");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Games", b =>
                {
                    b.Property<int?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GameId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.Property<int?>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("InfoId"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSchoolFinished")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUniversityFinished")
                        .HasColumnType("bit");

                    b.Property<int?>("LatestPostPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalComments")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReactions")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReplies")
                        .HasColumnType("int");

                    b.Property<int?>("TotalShares")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workorprofession")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoId");

                    b.HasIndex("LatestPostPostId");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Mangas", b =>
                {
                    b.Property<int?>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MangaId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MangaId");

                    b.ToTable("Manga");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Media", b =>
                {
                    b.Property<int?>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MediaId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateUploaded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Movies", b =>
                {
                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MovieId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Property<int?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PostId"));

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("ReactsId")
                        .HasColumnType("int");

                    b.Property<string>("Shortdesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewAnimes", b =>
                {
                    b.Property<int?>("ReviewAnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewAnimeId"));

                    b.Property<int?>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimesAnimeId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewAnimeId");

                    b.HasIndex("AnimesAnimeId");

                    b.ToTable("ReviewAnimes");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewComicBooks", b =>
                {
                    b.Property<int?>("ReviewComicBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewComicBookId"));

                    b.Property<int?>("ComicBookId")
                        .HasColumnType("int");

                    b.Property<int?>("ComicBooksComicBookId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewComicBookId");

                    b.HasIndex("ComicBooksComicBookId");

                    b.ToTable("ReviewComicBooks");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewGames", b =>
                {
                    b.Property<int?>("ReviewGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewGameId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewGameId");

                    b.HasIndex("GamesGameId");

                    b.ToTable("ReviewGames");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewMangas", b =>
                {
                    b.Property<int?>("ReviewMangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewMangaId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MangaId")
                        .HasColumnType("int");

                    b.Property<int?>("MangasMangaId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewMangaId");

                    b.HasIndex("MangasMangaId");

                    b.ToTable("ReviewMangas");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewMovies", b =>
                {
                    b.Property<int?>("ReviewMovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewMovieId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MoviesMovieId")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("ReviewMovies");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewTVSeries", b =>
                {
                    b.Property<int?>("ReviewTVSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ReviewTVSerieId"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TVSerieId")
                        .HasColumnType("int");

                    b.Property<int?>("TVSeriesTVSerieId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewTVSerieId");

                    b.HasIndex("TVSeriesTVSerieId");

                    b.ToTable("ReviewTVSeries");
                });

            modelBuilder.Entity("lcpsnapi.Classes.TVSeries", b =>
                {
                    b.Property<int?>("TVSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TVSerieId"));

                    b.Property<string>("AuthorsInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CastInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificationAge")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("TVSerieId");

                    b.ToTable("TVSerie");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Todo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DateT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfoId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Portugal",
                            Cover = "/assets/images/users/c_luigi.png",
                            DateBirthday = "1996-06-04T00:00:00",
                            DateRegistered = "2022-08-19T10:30:00",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            FirstName = "Luis",
                            Image = "/assets/images/users/luigi.png",
                            LastName = "Carvalho",
                            Password = "$2a$11$5h59HPYYimrBHqify7OUv.sunTLyHvL.Nec.6ayJuNFnLUcNE5rqu",
                            Pin = "$2a$11$jQrGRRJWu/fMhzmgTGyBoeS5DcL5YBiuxkQ7q3Fwxkc1TKGekvrWG",
                            PrivacyStatus = 0,
                            Role = 0,
                            Status = 1,
                            TypeFriend = 0,
                            Username = "luigicar96"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            Cover = "/assets/images/users/c_guest.png",
                            DateBirthday = "1995-05-03T00:00:00",
                            DateRegistered = "2022-08-31T15:50:00",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            FirstName = "Guest",
                            Image = "/assets/images/users/guest.png",
                            LastName = "Convidado",
                            Password = "$2a$11$8hvYLSUzahAZCyXHzGv7CeIGdJ1djanynxmCiDBB8GzU25Z6gWuaG",
                            Pin = "$2a$11$LcKHm9zdAxGXDbRKG6F06.bQ1rCIb5Xj7274JmksEqk.EnKlpfT7G",
                            PrivacyStatus = 1,
                            Role = 5,
                            Status = 0,
                            TypeFriend = 0,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.UsersToken", b =>
                {
                    b.Property<int?>("UsersTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UsersTokenId"));

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UsersTokenId");

                    b.ToTable("UserToken");

                    b.HasData(
                        new
                        {
                            UsersTokenId = 1,
                            Cover = "/assets/images/users/c_luigi.png",
                            DateCreated = new DateTime(2023, 1, 11, 13, 30, 10, 710, DateTimeKind.Utc).AddTicks(1591),
                            DateExp = "11/02/2023 13:30:10",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            Image = "/assets/images/users/luigi.png",
                            Password = "$2a$11$FoPw54ytpTaeVboP1cCti.Rt9LxPBiLDK9Rw2p0LKrNdpMNsoKJN.",
                            Pin = "$2a$11$y8PY1shvC6PJVKoCcPHujeoLsCx9REgvsxSLr2dGvAXz25KM4Bc5C",
                            Role = "superadmin",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbGhvc3QiLCJqdGkiOiJhYTNlZjVjZS00NmFmLTQ1NGEtYTE2ZC1iMTlkN2NhY2FlMWEiLCJpYXQiOiIxMS8wMS8yMDIzIDEzOjMwOjEwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imx1aWdpY2FyOTYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJzdXBlcmFkbWluIiwiZXhwIjoxNjc2MTIyMjEwLCJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJsb2NhbGhvc3QifQ.UIpddIh8-gd3k58cWsLfLAH__rEZXCeKzMb3V1BRWVQ",
                            Username = "luigicar96",
                            UsersId = 1
                        },
                        new
                        {
                            UsersTokenId = 2,
                            Cover = "/assets/images/users/c_guest.png",
                            DateCreated = new DateTime(2023, 1, 11, 13, 30, 11, 51, DateTimeKind.Utc).AddTicks(7735),
                            DateExp = "11/02/2023 13:30:11",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            Image = "/assets/images/users/guest.png",
                            Password = "$2a$11$Eia52k9RGydKyC2.cojdo.5z4pB6hwuwgJb3zKodYokhGMQjbYgam",
                            Pin = "$2a$11$TKcd4e4xSKHsUSKRHmeKaO2qhwxA.fUpJ74l3ukBRC5b7J6MQM9lu",
                            Role = "guest",
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbGhvc3QiLCJqdGkiOiJmMmUxMWRmNi0wZDUwLTQ4YzEtYTgwNy1hNGRmZGFiMjcwNTIiLCJpYXQiOiIxMS8wMS8yMDIzIDEzOjMwOjExIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd1ZXN0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZ3Vlc3QiLCJleHAiOjE2NzYxMjIyMTEsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.GoBtJ5NR4nPktXlhiUTWBlPDwnjAY3EwKqVLzDmvlyk",
                            Username = "guest",
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", null)
                        .WithMany("Attachments")
                        .HasForeignKey("PostsPostId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Users", null)
                        .WithMany("FriendsList")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryAnimes", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Animes", null)
                        .WithMany("Gallery")
                        .HasForeignKey("AnimesAnimeId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryComicBooks", b =>
                {
                    b.HasOne("lcpsnapi.Classes.ComicBooks", null)
                        .WithMany("Gallery")
                        .HasForeignKey("ComicBooksComicBookId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryGames", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Games", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GamesGameId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryMangas", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Mangas", null)
                        .WithMany("Gallery")
                        .HasForeignKey("MangasMangaId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryMovies", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Movies", null)
                        .WithMany("Gallery")
                        .HasForeignKey("MoviesMovieId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.GalleryTVSeries", b =>
                {
                    b.HasOne("lcpsnapi.Classes.TVSeries", null)
                        .WithMany("Gallery")
                        .HasForeignKey("TVSeriesTVSerieId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", "LatestPost")
                        .WithMany()
                        .HasForeignKey("LatestPostPostId");

                    b.Navigation("LatestPost");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewAnimes", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Animes", null)
                        .WithMany("Reviews")
                        .HasForeignKey("AnimesAnimeId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewComicBooks", b =>
                {
                    b.HasOne("lcpsnapi.Classes.ComicBooks", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ComicBooksComicBookId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewGames", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Games", null)
                        .WithMany("Reviews")
                        .HasForeignKey("GamesGameId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewMangas", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Mangas", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MangasMangaId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewMovies", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Movies", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MoviesMovieId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ReviewTVSeries", b =>
                {
                    b.HasOne("lcpsnapi.Classes.TVSeries", null)
                        .WithMany("Reviews")
                        .HasForeignKey("TVSeriesTVSerieId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Info", "Info")
                        .WithMany()
                        .HasForeignKey("InfoId");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Animes", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.ComicBooks", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Games", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Mangas", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Movies", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("lcpsnapi.Classes.TVSeries", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Navigation("FriendsList");
                });
#pragma warning restore 612, 618
        }
    }
}
