// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lcpsnapi.Context;

#nullable disable

namespace lcpsnapi.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lcpsnapi.Classes.Achievements", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateAchUnlocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjectiveCounter")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.Property<int?>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AttachmentId"), 1L, 1);

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("PostsPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("PostsPostId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.Property<int?>("FriendsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FriendsId"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFriends")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("FriendsId");

                    b.HasIndex("UsersId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.Property<int?>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("InfoId"), 1L, 1);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSchoolFinished")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUniversityFinished")
                        .HasColumnType("bit");

                    b.Property<int?>("LatestPostPostId")
                        .HasColumnType("int");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalComments")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReactions")
                        .HasColumnType("int");

                    b.Property<int?>("TotalReplies")
                        .HasColumnType("int");

                    b.Property<int?>("TotalShares")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workorprofession")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoId");

                    b.HasIndex("LatestPostPostId");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Media", b =>
                {
                    b.Property<int?>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MediaId"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateUploaded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Property<int?>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PostId"), 1L, 1);

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int");

                    b.Property<int?>("ReactsId")
                        .HasColumnType("int");

                    b.Property<string>("Shortdesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Todo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivacyStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TypeFriend")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersTokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InfoId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Portugal",
                            Cover = "/assets/images/users/c_luigi.png",
                            DateBirthday = "1996-06-04T00:00:00",
                            DateRegistered = "2022-08-19T10:30:00",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            FirstName = "Luis",
                            Image = "/assets/images/users/luigi.png",
                            LastName = "Carvalho",
                            Password = "1234",
                            Pin = "1234",
                            PrivacyStatus = 0,
                            Role = 0,
                            Status = 1,
                            TypeFriend = 0,
                            Username = "luigicar96"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            Cover = "/assets/images/users/c_guest.png",
                            DateBirthday = "1995-05-03T00:00:00",
                            DateRegistered = "2022-08-31T15:50:00",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            FirstName = "Guest",
                            Image = "/assets/images/users/guest.png",
                            LastName = "Convidado",
                            Password = "1234",
                            Pin = "1234",
                            PrivacyStatus = 1,
                            Role = 4,
                            Status = 0,
                            TypeFriend = 0,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.UsersToken", b =>
                {
                    b.Property<int?>("UsersTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UsersTokenId"), 1L, 1);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("UsersTokenId");

                    b.ToTable("UserToken");

                    b.HasData(
                        new
                        {
                            UsersTokenId = 1,
                            DateCreated = new DateTime(2022, 12, 20, 15, 26, 6, 297, DateTimeKind.Utc).AddTicks(7975),
                            DateExp = "20/01/2023 15:26:06",
                            Displayname = "Luis Carvalho",
                            Email = "luiscarvalho239@gmail.com",
                            Token = "",
                            Username = "luigicar96",
                            UsersId = 1
                        },
                        new
                        {
                            UsersTokenId = 2,
                            DateCreated = new DateTime(2022, 12, 20, 15, 26, 6, 297, DateTimeKind.Utc).AddTicks(8082),
                            DateExp = "20/01/2023 15:26:06",
                            Displayname = "Guest Convidado",
                            Email = "guest@localhost.loc",
                            Token = "",
                            Username = "guest",
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("lcpsnapi.Classes.Attachments", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", null)
                        .WithMany("Attachments")
                        .HasForeignKey("PostsPostId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Friends", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Users", null)
                        .WithMany("FriendsList")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Info", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Posts", "LatestPost")
                        .WithMany()
                        .HasForeignKey("LatestPostPostId");

                    b.Navigation("LatestPost");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.HasOne("lcpsnapi.Classes.Info", "Info")
                        .WithMany()
                        .HasForeignKey("InfoId");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Posts", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("lcpsnapi.Classes.Users", b =>
                {
                    b.Navigation("FriendsList");
                });
#pragma warning restore 612, 618
        }
    }
}
